# Dockerfile for sub operation
FROM node:14-alpine

WORKDIR /app

# Copy package.json and package-lock.json files and install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy the rest of the application files
COPY . .

# Expose the port your app runs on
EXPOSE 8080

# Specify the command to run your app
CMD ["node", "sub.js"]
